services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: movie_star
      POSTGRES_USER: movie_star
      POSTGRES_PASSWORD: movie_star
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-runtime
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_ENV=development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-runtime
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  db-data:
