root = "."
tmp_dir = "tmp"
build = "go build -o ./tmp/server ./cmd/api"
cmd = "./tmp/server"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
log = "air.log"

[log]
color = true

[build]
bin = "tmp/server"
cmd = "go build -o ./tmp/server ./cmd/api"
delay = 1000
exclude_dir = ["tmp", "vendor"]
include_ext = ["go"]
kill_delay = 500
stop_on_error = true
send_interrupt = true
